# Boilerplate github action code to setup CI environment for building and deploying app. 
# use in github action like:
# - name: Setup environment for building and releasing app 
#   uses: ./.github/actions/prepare-for-app-build.yml
name: 'Prepare for building and releasing app'
description: 'Do setup steps to setup the CI environment to be able to successfully build and deploy the app.'
runs:
  using: "composite"
  steps:
    - name: Setup Ruby to run Fastlane 
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Prepare app for building and deploying 
      shell: bash 
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_BASE64 }}" | base64 -d > "Remote Habits/GoogleService-Info.plist"
        echo "${{ secrets.ENV_FILE_B64 }}" | base64 -d > "Remote Habits/Env.swift"
        echo "${{ secrets.FIREBASE_APP_DISTRIBUTION_GOOGLE_AUTH }}" | base64 -d > firebase_appdistribution_service_account.json
        echo "${{ secrets.MATCH_GOOGLE_CLOUD_KEYS_B64 }}" | base64 -d > gc_keys.json
      env:
        GOOGLE_SERVICES_BASE64: "${{ secrets.GOOGLE_SERVICES_BASE64 }}"
        ENV_FILE_B64: "${{ secrets.ENV_FILE_B64 }}"
        FIREBASE_APP_DISTRIBUTION_GOOGLE_AUTH: ${{ secrets.FIREBASE_APP_DISTRIBUTION_GOOGLE_AUTH }}
        MATCH_GOOGLE_CLOUD_KEYS_B64: ${{ secrets.MATCH_GOOGLE_CLOUD_KEYS_B64 }}  
    - name: Install Fastlane 
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'list' # give action a lane that doesn't perform an action to get fastlane installed on machine to use later. 
        skip-tracking: true