import_from_git(
  url: "https://github.com/customerio/customerio-ios.git",
  branch: "levi/stable-builds-on-main", # The branch to checkout on the repository.
  path: "Apps/fastlane/Fastfile" # The path of the Fastfile in the repository.
)