# Deploy the app to stable. Not builds for development/QA
name: Deploy non-development builds 
on:
  push:
    branches: [main, beta, alpha]

env:
  XCODE_VERSION: "13.0"
  GITHUB_CONTEXT: ${{ toJSON(github) }} # used by fastlane for deploying app 

jobs:
  deploy-app:
    name: Deploy app
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment for building and releasing app 
        uses: ./.github/actions/prepare-for-app-build
        with:
          GOOGLE_SERVICES_BASE64: "${{ secrets.GOOGLE_SERVICES_BASE64 }}"
          ENV_FILE_B64: "${{ secrets.ENV_FILE_B64 }}"
          FIREBASE_APP_DISTRIBUTION_GOOGLE_AUTH: ${{ secrets.FIREBASE_APP_DISTRIBUTION_GOOGLE_AUTH }}
          MATCH_GOOGLE_CLOUD_KEYS_B64: ${{ secrets.MATCH_GOOGLE_CLOUD_KEYS_B64 }}          
            
      # Perform git related tasks inside of semantic-release because `git config user...` is already setup. It's easier to run commands in there with exec plugin.
      - name: Deploy app via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        id: semantic-release
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 18
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
            @semantic-release/exec@6
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }} # for semantic release git push access 
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }} # for firebase app distribution 
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT_B64: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT_B64 }}
          
      - name: Notify team of app deployment 
        uses: openhousepvt/slack@v1.3.2
        if: steps.semantic-release.outputs.new_release_published == 'true'
        with:
          status: 'success'
          version: ${{ steps.semantic-release.outputs.new_release_version }}
          platform: 'iOS Remote Habits new version deployed'
          channel: '#squad-mobile'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFY_RELEASES_WEBHOOK_URL }}