# Deploy the app to stable. Not builds for development/QA
name: Build app 

on:
  push:
    branches: [main]
  workflow_dispatch: # manually run the action
  pull_request:

jobs:
  deploy-app:
    name: Deploy app
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode to version we determine 
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14

    - name: Install CLI tools used in CI script 
      run: |
        brew install xcbeautify # used by fastlane for output 
    
    - name: Install tools from Gemfile (ruby language) used for building our apps with 
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true # cache tools to make builds faster in future 

    - name: Prepare app for building and deploying 
      shell: bash 
      run: |
        echo "${{ secrets.ENV_FILE_B64 }}" | base64 -d > "Remote Habits/Env.swift"        
          
    - name: Build app via Fastlane 
      uses: maierj/fastlane-action@v3.0.0
      with:
        lane: "ios build"
      env: 
        GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64: ${{ secrets.GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64 }}
        FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64 }}
          