name: Lint

on: [pull_request]

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install lint tools
        run: brew install swiftlint swiftformat
      - name: Running lint to verify it was run on local machine 
        # Script will fail if (1) the lint check failed or (2) for formatter formatted some code. 
        # If `make lint` is run on the local dev machine before pushing, this should pass. 
        run: |
          make lint && git diff --exit-code
      - name: Comment on PR if linting failed 
        uses: thollander/actions-comment-pull-request@v1
        # if: ${{ failure() }} # commenting out to test it works. 
        with:
          message: 'Friendly reminder to run `make lint` on code base, fix all lint errors, then push up the code again. Tip: [you can setup git hooks](https://github.com/customerio/RemoteHabits-iOS/blob/main/docs/dev-notes/DEVELOPMENT.md) to run `make lint` automatically for you during development.'